import 'package:flutter/material.dart';

const Color lightSkyBlueColor = Color(0xff82C7DF);
const Color darkSkyBlueColor = Color(0xff25abe0);
const Color redOpacityColor = Color.fromRGBO(231, 77, 77, 1);
const Color whiteColor = Colors.white;
const extraLightBlackColor = Color.fromARGB(255, 46, 46, 46);
const lightBlackColor = Color.fromARGB(255, 24, 24, 24);
const Color blackColor = Colors.black;
Color extraLightGreyColor = Colors.grey.shade100;
Color lightGreyColor = Colors.grey.shade400;
Color greyColor = Color(0xffF1F1F1);
Color mediumGreyColor = Colors.grey.shade600;
Color darkGreyColor = Colors.grey.shade700;
Color greyShade200Color = Colors.grey.shade200;
const Color blueGreyLight = Color(0xffe3e9f0);
const Color mediumBlueGreyColor = Color(0xff6d7989);
const Color darkBlueGreyColor = Color(0xff192E51);
const Color lightBlueGreyColor = Color(0xfffefeff);
const Color deepOrangeColor = Color.fromARGB(255, 255, 141, 20);
const Color scaffoldDarkBackgroundColor = Color(0x00ff4444);
