name: datacoup
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.14+10

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  extended_image: ^6.3.1
  amazon_cognito_identity_dart_2: ^3.0.3
  get_storage: ^2.0.3
  csc_picker: ^0.2.6
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  shimmer: ^2.0.0
  cached_network_image: ^3.0.0
  transparent_image: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  youtube_player_iframe: ^3.1.0
  like_button: ^2.0.5
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  amplify_flutter: ^0.6.10
  amplify_auth_cognito: ^0.6.10
  # country_code_picker: ^2.0.2
  country_picker: ^2.0.17
  flutter_svg: ^1.1.6
  carousel_slider: ^4.1.1
  global_configuration: ^2.0.0-nullsafety.1
  amplify_core: ^0.6.10
  flutter_launcher_icons: ^0.10.0
  rename: ^2.0.1
  flutter_inappwebview: ^5.7.2
  flutter_screenutil: ^5.6.1
  device_info_plus: ^8.1.0
  sleek_circular_slider: ^2.0.1
  pie_chart: ^5.3.2
  

# dependency_overrides:
#   modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app-logo-white.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway-Regular.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
