import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "home": "Home",
          "favourite": "Favourite",
          "quicks": "Quicks",
          "profile": "Profile",
          "account": "Account",
          "photos": "Photos",
          "videos": "Videos",
          "article": "Articles",
          "continue": "CONTINUE",
          "update": "UPDATE",
          "signUp": "SIGN UP",
          "sendOtp": "SEND OTP",
          "dontHaveAnAccount": "Don't have an account ?",
          "alreadyHaveAccount": "Already have an account?",
          "rememberMe": "Remember me",
          "forgotPassword": "Forgot Password ?",
          "fullName": "Full Name",
          "firstName": "First Name",
          "lastName": "Last Name",
          "gender": "Gender",
          "dob": "Date of Birth",
          "emailAddress": "Email Address",
          "phoneNumber": "Phone Number",
          "country": "Country",
          "weWillSendNotification":
              "We will send a confirmation code on the above {} to verify your account",
          "createAccount": "Create Account",
          "createNewAccount": "Create a new account",
          "updateAccount": "Update Account",
          "termsAndCondition": "Terms and Conditions",
          "privacyPolicy": "Privacy Policy",
          "email": "Email",
          "phone": "Phone",
          "password": "Password",
          "updateProfilePhoto": "Update Profile Photo",
          "language": "Language",
          "appSettings": "App Settings",
          "hindi": "Hindi",
          "english": "English",
          "appSetting": "App Settings",
          "quizzes": "Quizzes",
          "darkMode": "Dark Mode",
          "policyAndGuidelines": "Policy and Guidelines",
          "legal": "Legal",
          "help": "Help",
          "logOut": "Logout",
          "general": "General",
        },
        'hi_IN': {
          "home": "घर",
          "favourite": "पसंदीदा",
          "quicks": "लघु वीडियो",
          "profile": "पार्श्वचित्र",
          "account": "पार्श्वचित्र",
          "quizzes": "प्रश्नोत्तरी",
          "photos": "तस्वीरें",
          "videos": "वीडियो",
          "article": "लेख",
          "continue": "जारी रखें",
          "update": "अपडेट करें",
          "signUp": "नया बनाये",
          "sendOtp": "OTP भेजें",
          "dontHaveAnAccount": "खाता नहीं है ?",
          "alreadyHaveAccount": "पहले से ही एक खाता है ?",
          "rememberMe": "याद रखें",
          "forgotPassword": "पासवर्ड भूल गए ?",
          "fullName": "पूरा नाम",
          "firstName": "प्रथम नाम",
          "lastName": "सरनेम",
          "gender": "लिंग",
          "dob": "जन्म की तारीख",
          "emailAddress": "ईमेल",
          "phoneNumber": "फ़ोन नंबर",
          "country": "देश",
          "weWillSendNotification":
              "We will send a confirmation code on the above {} to verify your account",
          "createAccount": "खाता बनाएं",
          "createNewAccount": "नया खाता बनाएं",
          "updateAccount": "खाता अपडेट करें",
          "termsAndCondition": "नियम और शर्तें",
          "privacyPolicy": "गोपनीयता नीति",
          "email": "ईमेल",
          "phone": "फ़ोन",
          "password": "पासवर्ड",
          "updateProfilePhoto": "प्रोफ़ाइल तस्वीर अपडेट करें",
          "language": "भाषा",
          "appSettings": "एप्लिकेशन सेटिंग",
          "hindi": "हिन्दी",
          "english": "अंग्रेज़ी",
          "appSetting": "ऐप सेटिंग",
          "darkMode": "डार्क मोड",
          "policyAndGuidelines": "नीति और दिशानिर्देश",
          "legal": "कानूनी",
          "help": "मदद",
          "logOut": "लॉग आउट",
          "general": "सामान्य",
        }
      };
}
